### ISSUE TITLE
Add screenshots and description

### ISSUE THREAD

**Issue by oupson** [oupson/jxlviewer#7]
Add screenshots and description according to [Fastlane format](https://gitlab.com/-/snippets/1895688).

**Comment by OkyDooky** [comment]
Is this in preparation for F-Droid building? :O

**Comment by oupson** [comment]
> Is this in preparation for F-Droid building? :O

https://github.com/oupson/jxlviewer/issues/6#issue-1473164134 👀

**Comment by OkyDooky** [comment]
I'll take that as a "yes." Lol
Would be cool to see your app there. I have a feeling it'll help move other established image viewers and gallery apps for Android forward in adopting and supporting this format.

**Comment by oupson** [comment]
> I'll take that as a "yes." Lol

Yes this is planned :) Actually it will be on the [IzzyOnDroid ](https://apt.izzysoft.de/fdroid/) repo.

> Would be cool to see your app there. I have a feeling it'll help move other established image viewers and gallery apps for Android forward in adopting and supporting this format.

Yes, and releasing a standalone library to load jpegxl files is also [on the way](https://github.com/oupson/jxlviewer/issues/3).

**Comment by OkyDooky** [comment]
I figured Izzy would be a first stop before going to the main repository. But, if that's this app's only hosting repo (aside from here), then that's fone, since having that library should do a lot!
Thank you for doing this. I've gotten really excited about this format after reading up on it and I can hardly wait for it to be fully implemented everywhere, but I'm learning patience. Efforts like yours give me a lot of hope. Even if Google is being a poopyhead, I share Jon's (the creator) sentiment that it'll likely happen anyways.
Also, here's a graphic some anonymous poster made that you could use in discussions with someone:
![JXL_industry_support](https://user-images.githubusercontent.com/59938024/205467201-ad4f45b9-94fa-4e66-98be-1c1074b1e544.jpg)
